package render

import (
	"context"
	"io"
	"strings"

	"github.com/a-h/templ"
	"github.com/bluekeyes/go-gitdiff/gitdiff"
)

// ParseUnifiedDiff parses a unified-diff string (locally generated by go-udiff
// from two fetched blob versions) into the go-gitdiff file model. An empty input
// yields no files and no error (an unchanged / empty diff).
func ParseUnifiedDiff(unified string) ([]*gitdiff.File, error) {
	if strings.TrimSpace(unified) == "" {
		return nil, nil
	}
	files, _, err := gitdiff.Parse(strings.NewReader(unified))
	if err != nil {
		return nil, err
	}
	return files, nil
}

// diffLineKind classifies a rendered diff row for CSS styling.
type diffLineKind int

const (
	diffCtx diffLineKind = iota
	diffAdd
	diffDel
)

// diffRow is one rendered line of a hunk: the old/new line-number gutters
// (zero = "no number on this side") and the line content.
type diffRow struct {
	Kind    diffLineKind
	OldLine int64
	NewLine int64
	Content string
}

// diffHunk is a contiguous block of changes with its @@ header and rows.
type diffHunk struct {
	Header string
	Rows   []diffRow
}

// diffFileView is the prepared, proto-free view-model for one file's diff.
type diffFileView struct {
	Path      string
	IsBinary  bool
	IsNew     bool
	IsDeleted bool
	Added     int64
	Deleted   int64
	Hunks     []diffHunk
}

// Diff renders a slice of parsed diff files into an HTML diff table per file.
// Each file gets a header (path + add/del counts), and per-hunk a @@ header
// followed by per-line rows classed diff-add / diff-del / diff-ctx with
// old/new line-number gutters and data-old / data-new attributes (the
// line-comment hook). Line content is HTML-escaped by templ.
func Diff(files []*gitdiff.File) templ.Component {
	views := make([]diffFileView, 0, len(files))
	for _, file := range files {
		views = append(views, buildDiffFileView(file))
	}
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		return writeDiff(w, views)
	})
}

// writeDiff emits the per-file diff tables. All dynamic text is run through
// templ.EscapeString so repository content cannot inject markup.
func writeDiff(w io.Writer, views []diffFileView) error {
	sb := &strings.Builder{}
	for fi := range views {
		view := &views[fi]
		sb.WriteString(`<div class="diff-file" data-path="`)
		sb.WriteString(templ.EscapeString(view.Path))
		sb.WriteString(`">`)

		sb.WriteString(`<div class="diff-file-header"><span class="diff-file-path">`)
		sb.WriteString(templ.EscapeString(view.Path))
		sb.WriteString(`</span>`)
		if view.IsNew {
			sb.WriteString(`<span class="diff-file-tag diff-file-new">added</span>`)
		}
		if view.IsDeleted {
			sb.WriteString(`<span class="diff-file-tag diff-file-deleted">deleted</span>`)
		}
		sb.WriteString(`<span class="diff-file-stat diff-stat-add">+`)
		sb.WriteString(decimal(view.Added))
		sb.WriteString(`</span><span class="diff-file-stat diff-stat-del">−`)
		sb.WriteString(decimal(view.Deleted))
		sb.WriteString(`</span></div>`)

		if view.IsBinary {
			sb.WriteString(`<div class="diff-binary">Binary file changed</div></div>`)
			continue
		}

		sb.WriteString(`<table class="diff-table"><tbody>`)
		for hi := range view.Hunks {
			hunk := &view.Hunks[hi]
			sb.WriteString(`<tr class="diff-hunk"><td class="diff-gutter" colspan="2"></td><td class="diff-line diff-hunk-header">`)
			sb.WriteString(templ.EscapeString(hunk.Header))
			sb.WriteString(`</td></tr>`)
			for ri := range hunk.Rows {
				row := &hunk.Rows[ri]
				sb.WriteString(`<tr class="`)
				sb.WriteString(lineKindClass(row.Kind))
				sb.WriteString(`" data-old="`)
				sb.WriteString(templ.EscapeString(lineNumberText(row.OldLine)))
				sb.WriteString(`" data-new="`)
				sb.WriteString(templ.EscapeString(lineNumberText(row.NewLine)))
				sb.WriteString(`"><td class="diff-gutter diff-gutter-old">`)
				sb.WriteString(templ.EscapeString(lineNumberText(row.OldLine)))
				sb.WriteString(`</td><td class="diff-gutter diff-gutter-new">`)
				sb.WriteString(templ.EscapeString(lineNumberText(row.NewLine)))
				sb.WriteString(`</td><td class="diff-line"><span class="diff-sign">`)
				sb.WriteString(templ.EscapeString(lineSign(row.Kind)))
				sb.WriteString(`</span>`)
				sb.WriteString(templ.EscapeString(row.Content))
				sb.WriteString(`</td></tr>`)
			}
		}
		sb.WriteString(`</tbody></table></div>`)
	}
	_, err := io.WriteString(w, sb.String())
	return err
}

// buildDiffFileView converts a go-gitdiff File into the render view-model.
func buildDiffFileView(file *gitdiff.File) diffFileView {
	view := diffFileView{
		Path:      diffPath(file),
		IsBinary:  file.IsBinary,
		IsNew:     file.IsNew,
		IsDeleted: file.IsDelete,
	}
	for _, fragment := range file.TextFragments {
		hunk := diffHunk{Header: fragment.Header()}
		oldLine := fragment.OldPosition
		newLine := fragment.NewPosition
		for _, line := range fragment.Lines {
			row := diffRow{Content: strings.TrimSuffix(line.Line, "\n")}
			switch line.Op {
			case gitdiff.OpAdd:
				row.Kind = diffAdd
				row.NewLine = newLine
				newLine++
				view.Added++
			case gitdiff.OpDelete:
				row.Kind = diffDel
				row.OldLine = oldLine
				oldLine++
				view.Deleted++
			default: // gitdiff.OpContext
				row.Kind = diffCtx
				row.OldLine = oldLine
				row.NewLine = newLine
				oldLine++
				newLine++
			}
			hunk.Rows = append(hunk.Rows, row)
		}
		view.Hunks = append(view.Hunks, hunk)
	}
	return view
}

// diffPath returns the most informative path for a file diff: the new path for
// adds/modifies, the old path for deletes.
func diffPath(file *gitdiff.File) string {
	if file.NewName != "" {
		return file.NewName
	}
	return file.OldName
}

// lineNumberText renders a gutter cell value: empty string for a zero (the
// line does not exist on that side), the decimal otherwise.
func lineNumberText(n int64) string {
	if n <= 0 {
		return ""
	}
	return decimal(n)
}

// lineKindClass maps a diff line kind to its row CSS class.
func lineKindClass(kind diffLineKind) string {
	switch kind {
	case diffAdd:
		return "diff-add"
	case diffDel:
		return "diff-del"
	default:
		return "diff-ctx"
	}
}

// lineSign returns the leading +/-/space marker for a diff row.
func lineSign(kind diffLineKind) string {
	switch kind {
	case diffAdd:
		return "+"
	case diffDel:
		return "-"
	default:
		return " "
	}
}

// decimal formats a non-negative int64 as a decimal string.
func decimal(n int64) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	pos := len(buf)
	for n > 0 {
		pos--
		buf[pos] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[pos:])
}
