package render

import (
	"bytes"
	"strings"

	"github.com/a-h/templ"
	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
)

// Highlight tokenises src using a lexer chosen by filename and formats it with
// chroma's HTML formatter in class mode (so the shared /static/chroma.css
// stylesheet, generated by GenerateCSS against the same "github" style,
// provides all colours). Line numbers are emitted in table form.
//
// The returned component wraps the formatter output with templ.Raw — chroma
// output is safe to emit verbatim (no user-controlled tag injection).
func Highlight(filename string, src []byte) (templ.Component, error) {
	lexer := lexerFor(filename, src)

	iterator, err := chroma.Coalesce(lexer).Tokenise(nil, string(src))
	if err != nil {
		return nil, err
	}

	formatter := chromahtml.New(
		chromahtml.WithClasses(true),
		chromahtml.WithLineNumbers(true),
		chromahtml.LineNumbersInTable(true),
	)

	var buf bytes.Buffer
	if err := formatter.Format(&buf, styles.Get(chromaStyle), iterator); err != nil {
		return nil, err
	}
	return templ.Raw(buf.String()), nil
}

// LexerName returns a human-readable lexer label for display in the file view
// (e.g. "Go", "C++", "Plain Text"). It never returns an empty string.
func LexerName(filename string, src []byte) string {
	return lexerFor(filename, src).Config().Name
}

// lexerFor resolves the best chroma lexer for a file: lexers.Match by filename
// first (fastest), then lexers.Analyse on a content snippet (magic bytes /
// shebangs), then the plain-text fallback.
func lexerFor(filename string, src []byte) chroma.Lexer {
	// Match by filename extension / known names.
	if l := lexers.Match(filename); l != nil {
		return l
	}

	// Determine the basename so we don't confuse lexers.Analyse with a path.
	base := filename
	if idx := strings.LastIndexByte(filename, '/'); idx >= 0 {
		base = filename[idx+1:]
	}

	// Content-based analysis (shebangs, magic bytes, etc.).
	snippet := src
	if len(snippet) > 8192 {
		snippet = snippet[:8192]
	}
	if l := lexers.Analyse(base + "\n" + string(snippet)); l != nil {
		return l
	}

	return lexers.Fallback
}
